### ISSUE TITLE
Display for esp32 oled

### ISSUE THREAD

**Issue by raouland** [pbecchi/SmartSol_Firmware#2]
It would be good to have the ability to turn on and off oled screen on esp32 and have it display rssi and station number when on

**Comment by pbecchi** [comment]
Working on it. Done by tomorrow!

**Comment by pbecchi** [comment]
I plan to make new release of SmartSolenoidEsp32 by end of the week including this change # @

**Comment by pbecchi** [comment]
#new SmartSolenoid ESP32 relaesed
